# Data ingestion

For video notes on these materials, please see the adjoining [video notes](03-03-data-ingest-video-notes.ipynb). Then complete this exercise. 

First watch the video and login to grading:

In [1]:
# Don't change this cell; just run it. 
from IPython.display import IFrame
IFrame('https://1813261-1.kaf.kaltura.com/media/t/1_odixlrd8/133896931', width=800, height=560)

from client.api.notebook import Notebook
ok = Notebook('03-03-data-ingest.ok')

Assignment: 03-03 Data Ingestion
OK, version v1.14.15



1. **Write code to read data from the file `exer1.txt`.**
Put the data into the numpy array `exer1`

In [2]:
%more exer1.txt

In [3]:
# fill in details ... 
import numpy as np
exer1 = np.loadtxt('exer1.txt', delimiter=',')
exer1

array([[25. , 25.5, 10.4],
       [10. , 15. , 25.5],
       [ 9. ,  2. ,  7. ]])

In [4]:
_ = ok.grade('q01')  # run this to check your answer

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



2. **Write code to read data from the file `exer2.txt`.** Put the result into `exer2`.

In [5]:
%more exer2.txt

In [6]:
# fill in details ... 
exer2 = np.loadtxt('exer2.txt')  
exer2

array([[25. , 25.5, 10.4],
       [10. , 15. , 25.5],
       [ 9. ,  2. ,  7. ]])

In [7]:
_ = ok.grade('q02')  # run this to check your work

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



2. **Write code to read data from the file `exer3.txt`.** Put the result into `exer3`.

In [8]:
%more exer3.txt

In [9]:
# fill in details ... 
exer3 = np.genfromtxt('exer3.txt',delimiter = (4,4,4))
exer3

array([[25. , 25.5, 10.4],
       [10. , 15. , 25.5],
       [ 9. ,  2. ,  7. ]])

In [10]:
_ = ok.grade('q03')  # run this to check your answer

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



(A personal note: You might think this file format is really clueless. It contains, however, the exact same data as the other two files. This kind of column run-together is common in outputs of scientific computing, and *fixed-width parsing is the only way to unravel it!* These exercises are chosen from *my personal experience in frustrating data wrangling* to get data into python and other languages! -- Prof. Couch)

4. (Advanced) Write code to input the data in `exer4.txt`. Make the third column an integer rather than floating point. Hint: look at the `dtype` field in the documentation for `genfromtxt` and use it to define the field types. Consider allowing the system to figure it out via `dtype=None` 

In [11]:
%more exer4.txt

In [12]:
# fill in details ...
exer4 = np.genfromtxt('exer4.txt',delimiter = (4,4,4),dtype = [('f8'),('f8'),('i8')])
print(exer4)

[(20. , 30. ,  4) (40.5, 50.5, 30) (60.2, 70.3, 50)]


See SciPy [Structured Arrays and Structured Datatypes](https://docs.scipy.org/doc/numpy/user/basics.rec.html) for details.

In [13]:
type(exer4[0][2])

numpy.int64

In [14]:
_ = ok.grade('q04')  # run this to check your answer

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



### Afterword: what is an nparray? 
In this example, the result will be an `nparray` of tuples rather than a regular `nparray` of numbers. Why? *A regular `nparray` requires elements of the same type!*. Compare the above with the output from exercise 3 above. All elements are float, so that's a regular `nparray`. When you violate that restriction, `numpy` automatically gives you a tuple rather than a list of values. 

5. (Advanced) As in problem 4, read data from `exer5.txt`, and additionally label the columns 'carbon', 'nitrogen', 'oxygen'. Put the result into exer5.

In [17]:
%more exer5.txt

In [18]:
def read_fixed_format_named_file(filename):
    ...

    exer5 = read_fixed_format_named_file("exer5.txt")
exer5

NameError: name 'exer5' is not defined

In [19]:
# use this to test your work 
for key in exer5.dtype.names:
    print('{} is {}'.format(key, exer5[key]))

NameError: name 'exer5' is not defined

Note that these are real `ndarray` vectors, not `tuple`s, because they each contain a single type of elements. 

In [20]:
_ = ok.grade('q05')  # run this to check your answer

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Question 5 > Suite 1 > Case 1

>>> print(exer5)
NameError: name 'exer5' is not defined

# Error: expected
#     [(20. , 30. ,  4) (40.5, 50.5, 30) (60.2, 70.3, 50)]
# but got
#     Traceback (most recent call last):
#       ...
#     NameError: name 'exer5' is not defined

Run only this test case with "python3 ok -q q05 --suite 1 --case 1"
---------------------------------------------------------------------
Test summary
    Passed: 0
    Failed: 1
[k..........] 0.0% passed



# When you are done with this notebook, 
* Save and checkpoint. 
* Ensure that the name of this file is precisely `03-03-data-ingest.ipynb`. 
* <del>Change `ready` to `True` in the cell below. </del>
* <del>Run the cell below to submit your work for grading. </del>
* Save and checkpoint the notebook. 

In [ ]:
ready = True  # change to True when ready to submit
print("submitting file {} for assignment {} as user {}".format(ok.assignment.src[0], 
                                                               ok.assignment.name, 
                                                               ok.assignment.get_student_email()))
if not ready:
    raise Exception("change ready to True when ready to submit")
_ = ok.submit()

ERROR  | auth.py:102 | {'error': 'invalid_grant'}


Performing authentication
